/* Generated by bin2c, do not edit manually */
#ifndef ___driver_m1_h_included
#define ___driver_m1_h_included

/* Contents of file build/202-m1.bin */
extern const long int driver_m1_size;
extern const unsigned char driver_m1[16384];

#endif    /* ___driver_m1_h_included */
