/* Generated by bin2c, do not edit manually */
#ifndef ___home_robplt_Programming_vgm2mlm_src_lib_driver_p1_h_included
#define ___home_robplt_Programming_vgm2mlm_src_lib_driver_p1_h_included

/* Contents of file prom.bin */
extern const long int driver_p1_size;
extern const unsigned char driver_p1[4096];

#endif    /* ___home_robplt_Programming_vgm2mlm_src_lib_driver_p1_h_included */
