/* Generated by bin2c, do not edit manually */
#ifndef ___driver_p1_h_included
#define ___driver_p1_h_included

/* Contents of file prom.bin */
extern const long int driver_p1_size;
extern const unsigned char driver_p1[3494];

#endif    /* ___driver_p1_h_included */
